#!/usr/bin/env python3
"""Build a classic (non-module) copy of the vendored drawably library.

  python3 tools/drawably-classic.py

WHY: drawably ships as ES modules. Chrome refuses to load ES modules from a page
opened straight from disk (file://): "blocked by CORS policy ... origin 'null'".
So the sketches silently never appeared when the site was opened by double
clicking index.html. A plain <script src> DOES load from file://, so this turns
the modules into one classic script that sets window.drawably.

HOW: each module in assets/vendor/drawably/dist becomes its own function scope,
in dependency order (prng -> rough -> controls -> composites). `import {a} from
"./x.js"` becomes `var a = __x.a`, `export function f` becomes `function f` plus
an entry in that scope's return value, and index.js's re-exports become the
public window.drawably object. It refuses to guess: any import/export form it
does not recognise aborts the build rather than producing a broken file.

Re-run after upgrading drawably (see HANDOFF "drawably, vendored").
"""
import io, os, re, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
DIST = os.path.join(ROOT, "assets", "vendor", "drawably", "dist")
OUT = os.path.join(ROOT, "assets", "vendor", "drawably", "drawably.classic.js")
ORDER = ["prng", "rough", "controls", "composites"]

IMPORT = re.compile(r'^import \{([^}]*)\} from "\./([a-z]+)\.js";\s*$')
EXPORT_DECL = re.compile(r'^export (function|const|let|class) ([A-Za-z_$][\w$]*)')
REEXPORT = re.compile(r'^export \{([^}]*)\} from "\./([a-z]+)\.js";\s*$')

def names(group):
    out = []
    for part in group.split(","):
        part = part.strip()
        if not part:
            continue
        bits = [b.strip() for b in part.split(" as ")]
        out.append((bits[0], bits[-1]))          # (source name, local name)
    return out

def read(name):
    return io.open(os.path.join(DIST, name + ".js"), encoding="utf-8").read()

exports_of = {}
chunks = []
for mod in ORDER:
    body, exports, preamble = [], [], []
    for ln in read(mod).split("\n"):
        m = IMPORT.match(ln)
        if m:
            src = m.group(2)
            if src not in exports_of:
                sys.exit("ABORT: %s imports %s before it is built" % (mod, src))
            for s, local in names(m.group(1)):
                if s not in exports_of[src]:
                    sys.exit("ABORT: %s imports %s.%s, which it does not export" % (mod, src, s))
                preamble.append("    var %s = __%s.%s;" % (local, src, s))
            continue
        m = EXPORT_DECL.match(ln)
        if m:
            exports.append(m.group(2))
            body.append(ln[len("export "):])
            continue
        if ln.startswith("import ") or ln.startswith("export "):
            sys.exit("ABORT: unrecognised module syntax in %s.js: %s" % (mod, ln[:100]))
        body.append(ln)
    exports_of[mod] = exports
    chunks.append("  var __%s = (function () {" % mod)
    chunks.extend(preamble)
    chunks.extend(("    " + l) if l.strip() else "" for l in body)
    chunks.append("    return { %s };" % ", ".join("%s: %s" % (e, e) for e in exports))
    chunks.append("  })();")

public = []
for ln in read("index").split("\n"):
    if not ln.strip():
        continue
    m = REEXPORT.match(ln)
    if not m:
        sys.exit("ABORT: unrecognised line in index.js: %s" % ln[:100])
    src = m.group(2)
    for s, local in names(m.group(1)):
        if s not in exports_of.get(src, []):
            sys.exit("ABORT: index.js re-exports %s.%s, which does not exist" % (src, s))
        public.append("    %s: __%s.%s" % (local, src, s))

version = "unknown"
pkg = os.path.join(ROOT, "assets", "vendor", "drawably", "..", "..", "..", "assets", "vendor", "drawably", "LICENSE")
header = """/* drawably, classic-script build. GENERATED by tools/drawably-classic.py from
   assets/vendor/drawably/dist (drawably 0.4.2, MIT, see LICENSE beside this
   file). Do not edit by hand: re-run the script instead.
   Exists because Chrome will not load ES modules from file://, so the module
   build never ran when the site was opened straight from disk. */
(function (global) {
  "use strict";
"""
footer = "  global.drawably = {\n%s\n  };\n})(typeof window !== \"undefined\" ? window : this);\n" % ",\n".join(public)
io.open(OUT, "w", encoding="utf-8").write(header + "\n".join(chunks) + "\n" + footer)
print("wrote %s (%d bytes, %d public names)" % (os.path.relpath(OUT, ROOT), os.path.getsize(OUT), len(public)))
